/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: healpix.i

#define SWIGMODULE healpix

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "vec3.h"
#include "geom_utils.h"
#include "healpix_base.h"
#include "healpix_map.h"


#include <vector>
#include <stdexcept>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_healpix_09aa05d3d2b4025d(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_healpix_09aa05d3d2b4025d(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_Vec3Floats_x_set_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->x = arg2;
  
}


double _wrap_Vec3Floats_x_get_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  result = (double) ((arg1)->x);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_Vec3Floats_y_set_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->y = arg2;
  
}


double _wrap_Vec3Floats_y_get_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  result = (double) ((arg1)->y);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_Vec3Floats_z_set_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  if (arg1) (arg1)->z = arg2;
  
}


double _wrap_Vec3Floats_z_get_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  result = (double) ((arg1)->z);
  _swig_go_result = result; 
  return _swig_go_result;
}


vec3_t< double > *_wrap_new_Vec3Floats__SWIG_0_healpix_09aa05d3d2b4025d() {
  vec3_t< double > *result = 0 ;
  vec3_t< double > *_swig_go_result;
  
  
  result = (vec3_t< double > *)new vec3_t< double >();
  *(vec3_t< double > **)&_swig_go_result = (vec3_t< double > *)result; 
  return _swig_go_result;
}


vec3_t< double > *_wrap_new_Vec3Floats__SWIG_1_healpix_09aa05d3d2b4025d(double _swig_go_0, double _swig_go_1, double _swig_go_2) {
  double arg1 ;
  double arg2 ;
  double arg3 ;
  vec3_t< double > *result = 0 ;
  vec3_t< double > *_swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = (double)_swig_go_2; 
  
  result = (vec3_t< double > *)new vec3_t< double >(arg1,arg2,arg3);
  *(vec3_t< double > **)&_swig_go_result = (vec3_t< double > *)result; 
  return _swig_go_result;
}


void _wrap_Vec3Floats_Set_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1, double _swig_go_2, double _swig_go_3) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  double arg3 ;
  double arg4 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = (double)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  
  (arg1)->Set(arg2,arg3,arg4);
  
}


void _wrap_Vec3Floats_set_z_phi_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1, double _swig_go_2) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  double arg3 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = (double)_swig_go_2; 
  
  (arg1)->set_z_phi(arg2,arg3);
  
}


void _wrap_Vec3Floats_Normalize_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  (arg1)->Normalize();
  
}


vec3_t< double > *_wrap_Vec3Floats_Norm_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  vec3_t< double > result;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  result = ((vec3_t< double > const *)arg1)->Norm();
  *(vec3_t< double > **)&_swig_go_result = new vec3_t< double >(result); 
  return _swig_go_result;
}


double _wrap_Vec3Floats_Length_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  result = (double)((vec3_t< double > const *)arg1)->Length();
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_Vec3Floats_SquaredLength_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  result = (double)((vec3_t< double > const *)arg1)->SquaredLength();
  _swig_go_result = result; 
  return _swig_go_result;
}


vec3_t< double > *_wrap_Vec3Floats_invert_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  vec3_t< double > result;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  result = ((vec3_t< double > const *)arg1)->operator -();
  *(vec3_t< double > **)&_swig_go_result = new vec3_t< double >(result); 
  return _swig_go_result;
}


void _wrap_Vec3Floats_Flip_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  (arg1)->Flip();
  
}


vec3_t< double > *_wrap_Vec3Floats_add_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, vec3_t< double > *_swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  vec3_t< double > *arg2 = 0 ;
  vec3_t< double > result;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = *(vec3_t< double > **)&_swig_go_1; 
  
  result = ((vec3_t< double > const *)arg1)->operator +((vec3_t< double > const &)*arg2);
  *(vec3_t< double > **)&_swig_go_result = new vec3_t< double >(result); 
  return _swig_go_result;
}


vec3_t< double > *_wrap_Vec3Floats_addInPlace_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, vec3_t< double > *_swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  vec3_t< double > *arg2 = 0 ;
  vec3_t< double > *result = 0 ;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = *(vec3_t< double > **)&_swig_go_1; 
  
  result = (vec3_t< double > *) &(arg1)->operator +=((vec3_t< double > const &)*arg2);
  *(vec3_t< double > **)&_swig_go_result = result; 
  return _swig_go_result;
}


vec3_t< double > *_wrap_Vec3Floats_subtract_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, vec3_t< double > *_swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  vec3_t< double > *arg2 = 0 ;
  vec3_t< double > result;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = *(vec3_t< double > **)&_swig_go_1; 
  
  result = ((vec3_t< double > const *)arg1)->operator -((vec3_t< double > const &)*arg2);
  *(vec3_t< double > **)&_swig_go_result = new vec3_t< double >(result); 
  return _swig_go_result;
}


vec3_t< double > *_wrap_Vec3Floats_subtractInPlace_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, vec3_t< double > *_swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  vec3_t< double > *arg2 = 0 ;
  vec3_t< double > *result = 0 ;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = *(vec3_t< double > **)&_swig_go_1; 
  
  result = (vec3_t< double > *) &(arg1)->operator -=((vec3_t< double > const &)*arg2);
  *(vec3_t< double > **)&_swig_go_result = result; 
  return _swig_go_result;
}


vec3_t< double > *_wrap_Vec3Floats_multiply_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  vec3_t< double > result;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = ((vec3_t< double > const *)arg1)->operator *(arg2);
  *(vec3_t< double > **)&_swig_go_result = new vec3_t< double >(result); 
  return _swig_go_result;
}


vec3_t< double > *_wrap_Vec3Floats_divide_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  vec3_t< double > result;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = ((vec3_t< double > const *)arg1)->operator /(arg2);
  *(vec3_t< double > **)&_swig_go_result = new vec3_t< double >(result); 
  return _swig_go_result;
}


vec3_t< double > *_wrap_Vec3Floats_multiplyInPlace_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0, double _swig_go_1) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  double arg2 ;
  vec3_t< double > *result = 0 ;
  vec3_t< double > *_swig_go_result;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  
  result = (vec3_t< double > *) &(arg1)->operator *=(arg2);
  *(vec3_t< double > **)&_swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_Vec3Floats_healpix_09aa05d3d2b4025d(vec3_t< double > *_swig_go_0) {
  vec3_t< double > *arg1 = (vec3_t< double > *) 0 ;
  
  arg1 = *(vec3_t< double > **)&_swig_go_0; 
  
  delete arg1;
  
}


double _wrap_Healpix_undef_get_healpix_09aa05d3d2b4025d() {
  double result;
  double _swig_go_result;
  
  
  result = (double)(double)Healpix_undef;
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_RING_healpix_09aa05d3d2b4025d() {
  Healpix_Ordering_Scheme result;
  intgo _swig_go_result;
  
  
  result = RING;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_NEST_healpix_09aa05d3d2b4025d() {
  Healpix_Ordering_Scheme result;
  intgo _swig_go_result;
  
  
  result = NEST;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


Healpix_Map< double > *_wrap_new_HEALPixMap__SWIG_0_healpix_09aa05d3d2b4025d() {
  Healpix_Map< double > *result = 0 ;
  Healpix_Map< double > *_swig_go_result;
  
  
  result = (Healpix_Map< double > *)new Healpix_Map< double >();
  *(Healpix_Map< double > **)&_swig_go_result = (Healpix_Map< double > *)result; 
  return _swig_go_result;
}


Healpix_Map< double > *_wrap_new_HEALPixMap__SWIG_1_healpix_09aa05d3d2b4025d(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  Healpix_Ordering_Scheme arg2 ;
  Healpix_Map< double > *result = 0 ;
  Healpix_Map< double > *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (Healpix_Ordering_Scheme)_swig_go_1; 
  
  result = (Healpix_Map< double > *)new Healpix_Map< double >(arg1,arg2);
  *(Healpix_Map< double > **)&_swig_go_result = (Healpix_Map< double > *)result; 
  return _swig_go_result;
}


long long _wrap_HEALPixMap_pix2ring_healpix_09aa05d3d2b4025d(Healpix_Map< double > *_swig_go_0, long long _swig_go_1) {
  Healpix_Map< double > *arg1 = (Healpix_Map< double > *) 0 ;
  long arg2 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(Healpix_Map< double > **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  result = (long)(arg1)->pix2ring(arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_delete_HEALPixMap_healpix_09aa05d3d2b4025d(Healpix_Map< double > *_swig_go_0) {
  Healpix_Map< double > *arg1 = (Healpix_Map< double > *) 0 ;
  
  arg1 = *(Healpix_Map< double > **)&_swig_go_0; 
  
  delete arg1;
  
}


double _wrap_orientation_healpix_09aa05d3d2b4025d(vec3_t< float64 > *_swig_go_0, vec3_t< float64 > *_swig_go_1) {
  vec3 *arg1 = 0 ;
  vec3 *arg2 = 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(vec3 **)&_swig_go_0; 
  arg2 = *(vec3 **)&_swig_go_1; 
  
  result = (double)orientation((vec3_t< float64 > const &)*arg1,(vec3_t< float64 > const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_v_angle_healpix_09aa05d3d2b4025d(vec3_t< float64 > *_swig_go_0, vec3_t< float64 > *_swig_go_1) {
  vec3 *arg1 = 0 ;
  vec3 *arg2 = 0 ;
  double result;
  double _swig_go_result;
  
  arg1 = *(vec3 **)&_swig_go_0; 
  arg2 = *(vec3 **)&_swig_go_1; 
  
  result = (double)v_angle((vec3_t< float64 > const &)*arg1,(vec3_t< float64 > const &)*arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_cosdist_zphi_healpix_09aa05d3d2b4025d(double _swig_go_0, double _swig_go_1, double _swig_go_2, double _swig_go_3) {
  double arg1 ;
  double arg2 ;
  double arg3 ;
  double arg4 ;
  double result;
  double _swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = (double)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  
  result = (double)cosdist_zphi(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_find_enclosing_circle_healpix_09aa05d3d2b4025d(std::vector< vec3_t< float64 > > *_swig_go_0, vec3_t< float64 > *_swig_go_1, double *_swig_go_2) {
  std::vector< vec3 > *arg1 = 0 ;
  vec3 *arg2 = 0 ;
  double *arg3 = 0 ;
  
  arg1 = *(std::vector< vec3 > **)&_swig_go_0; 
  arg2 = *(vec3 **)&_swig_go_1; 
  arg3 = *(double **)&_swig_go_2; 
  
  find_enclosing_circle((std::vector< vec3_t< float64 > > const &)*arg1,*arg2,*arg3);
  
}


#ifdef __cplusplus
}
#endif

